apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mp-kafka-rest-proxy.fullname" . }}
  labels:
    {{- include "mp-kafka-rest-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mp-kafka-rest-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mp-kafka-rest-proxy.selectorLabels" . | nindent 8 }}
      annotations:
        forceRecreate: {{ add .Values.global.recreationFlag .Values.recreationFlag | quote}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ required "A valid .Values.global.mpKafkaRestProxyPortName entry required!" .Values.global.mpKafkaRestProxyPortName }}
              containerPort: {{ required "A valid .Values.global.mpKafkaRestProxyPort entry required!" .Values.global.mpKafkaRestProxyPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ required "A valid .Values.global.mpKafkaRestProxyPort entry required!" .Values.global.mpKafkaRestProxyPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ required "A valid .Values.global.mpKafkaRestProxyPort entry required!" .Values.global.mpKafkaRestProxyPort }}

          envFrom:
            - configMapRef:
                name: {{ template "mp-kafka-rest-proxy.fullname" . }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
