apiVersion: v1
kind: Service
metadata:
  name: {{ include "mp-stream-api.fullname" . }}
  labels:
    {{- include "mp-stream-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "A valid .Values.global.mpStreamAPIPort entry required!" .Values.global.mpStreamAPIPort }}
      targetPort: {{ required "A valid .Values.global.mpStreamAPIPort entry required!" .Values.global.mpStreamAPIPort }}
      protocol: TCP
      name: {{ required "A valid .Values.global.mpStreamAPIPortName entry required!" .Values.global.mpStreamAPIPortName }}
  selector:
    {{- include "mp-stream-api.selectorLabels" . | nindent 4 }}
