replicaCount: 1

image:
  repository: 543164192837.dkr.ecr.eu-central-1.amazonaws.com/mp-stream-api
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#####################################################################################
################## USER SUPPLIED VALUES IN MAIN VALUES.YAML #########################
#####################################################################################

recreationFlag: 1

global:
  namespaceName: ""
  recreationFlag: 1
  mpStreamAPIPort: 8060
  mpStreamAPIPortName: http-8060

kafkaClusterId: ""
cpKafkaRestPort: 8082

service:
  type: ClusterIP

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetAverageCPUUtilization: 70
  targetAverageMemoryUtilization: 70

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  failureThreshold: 30
readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  failureThreshold: 30

#####################################################################################
################## USER SUPPLIED VALUES IN MAIN VALUES.YAML #########################
#####################################################################################
nodeSelector: {}

tolerations: []

affinity: {}
